# Generated by Django 3.0 on 2021-01-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_category', models.CharField(choices=[('Kids', 'Kids'), ('Women', 'Women'), ('men', 'men')], max_length=100)),
                ('product_dec', models.TextField(max_length=100)),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
