# Generated by Django 3.0 on 2021-01-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_dec',
            new_name='product_desc',
        ),
    ]
